/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfirstapplication;

import java.util.ArrayList;
import java.awt.*;
import javax.swing.*;
import java.applet.AudioClip;
import java.io.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import sun.audio.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**i
 *
 * @author Asus
 */
public class CoctailShop extends javax.swing.JFrame {
      boolean b1=false;
        ArrayList<Ingredients> ingList =new ArrayList<Ingredients>();
      private Blender blender= new Blender();
      ArrayList<Cup>cups=new ArrayList<>();
  

    /**
     * Creates new form CoctailShop
     */
    public CoctailShop() {
        initComponents();
        
        
    }

    
   
      
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientsList = new javax.swing.JList<>();
        color2Panel = new java.awt.Panel();
        color1Panel1 = new javax.swing.JPanel();
        color1Panel = new javax.swing.JPanel();
        color3Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        caloriesLable = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        caloriesLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cupPanel2 = new javax.swing.JPanel();
        cupPanel1 = new javax.swing.JPanel();
        cupPanel3 = new javax.swing.JPanel();
        cupPanel5 = new javax.swing.JPanel();
        cupPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        cupTextArea = new java.awt.TextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cupPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coctail Shop");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 723, 810, 0);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\apple-picking-clipart-26.jpg")); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(250, 380, 60, 80);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\banana.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(340, 380, 60, 80);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\orange-clipart-8.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(440, 380, 60, 80);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\stro.jpg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(530, 380, 60, 80);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\kiwi-fruit-cartoon-vector-1350776.jpg")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(620, 380, 60, 80);

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\pineapple-painted-fruit-graphic-art-cartoon-vector-illustration-77598913.jpg")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(160, 380, 60, 80);

        jLabel2.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcom to our Shop");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(270, 240, 250, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("chose your favorite ingredients to make your cocktail : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 340, 520, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Fruits :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 420, 70, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("Extra ingredients : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 550, 180, 16);

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\milk.jpg")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(260, 520, 70, 80);

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\suger.jpg")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(370, 520, 70, 80);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\96215581_265519727961542_7543470788196696064_n.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 30, 700, 627);

        jTabbedPane1.addTab("Welcom", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        ingredientsList.setSelectionBackground(new java.awt.Color(153, 0, 102));
        jScrollPane1.setViewportView(ingredientsList);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(520, 70, 180, 260);

        color2Panel.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout color2PanelLayout = new javax.swing.GroupLayout(color2Panel);
        color2Panel.setLayout(color2PanelLayout);
        color2PanelLayout.setHorizontalGroup(
            color2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        color2PanelLayout.setVerticalGroup(
            color2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel5.add(color2Panel);
        color2Panel.setBounds(70, 130, 80, 70);

        color1Panel1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout color1Panel1Layout = new javax.swing.GroupLayout(color1Panel1);
        color1Panel1.setLayout(color1Panel1Layout);
        color1Panel1Layout.setHorizontalGroup(
            color1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        color1Panel1Layout.setVerticalGroup(
            color1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel5.add(color1Panel1);
        color1Panel1.setBounds(150, 130, 30, 70);

        javax.swing.GroupLayout color1PanelLayout = new javax.swing.GroupLayout(color1Panel);
        color1Panel.setLayout(color1PanelLayout);
        color1PanelLayout.setHorizontalGroup(
            color1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        color1PanelLayout.setVerticalGroup(
            color1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel5.add(color1Panel);
        color1Panel.setBounds(70, 130, 30, 60);

        color3Panel.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout color3PanelLayout = new javax.swing.GroupLayout(color3Panel);
        color3Panel.setLayout(color3PanelLayout);
        color3PanelLayout.setHorizontalGroup(
            color3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        color3PanelLayout.setVerticalGroup(
            color3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.add(color3Panel);
        color3Panel.setBounds(80, 190, 90, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\blender-hi.png")); // NOI18N
        jPanel5.add(jLabel6);
        jLabel6.setBounds(40, 30, 200, 360);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(70, 140, 30, 50);

        jButton10.setBackground(new java.awt.Color(204, 153, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButton10.setText("Blend");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10);
        jButton10.setBounds(80, 420, 87, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Ingredients List : ");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(530, 30, 180, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("To remove an ingredient chose it and click remove button ");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(370, 340, 390, 16);

        jButton11.setBackground(new java.awt.Color(153, 0, 153));
        jButton11.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton11.setText("remove");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11);
        jButton11.setBounds(550, 380, 81, 25);
        jPanel5.add(jLabel9);
        jLabel9.setBounds(180, 520, 41, 16);

        caloriesLable.setBackground(new java.awt.Color(0, 51, 51));
        caloriesLable.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jPanel5.add(caloriesLable);
        caloriesLable.setBounds(0, 520, 740, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Blender Capacity is 1.5 litter");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(250, 40, 210, 17);

        caloriesLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jPanel5.add(caloriesLabel2);
        caloriesLabel2.setBounds(0, 610, 710, 40);

        jTabbedPane1.addTab("Blend", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        cupPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cupPanel2Layout = new javax.swing.GroupLayout(cupPanel2);
        cupPanel2.setLayout(cupPanel2Layout);
        cupPanel2Layout.setHorizontalGroup(
            cupPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        cupPanel2Layout.setVerticalGroup(
            cupPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel4.add(cupPanel2);
        cupPanel2.setBounds(100, 110, 40, 130);

        cupPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cupPanel1Layout = new javax.swing.GroupLayout(cupPanel1);
        cupPanel1.setLayout(cupPanel1Layout);
        cupPanel1Layout.setHorizontalGroup(
            cupPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cupPanel1Layout.setVerticalGroup(
            cupPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel4.add(cupPanel1);
        cupPanel1.setBounds(80, 110, 20, 130);

        cupPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cupPanel3Layout = new javax.swing.GroupLayout(cupPanel3);
        cupPanel3.setLayout(cupPanel3Layout);
        cupPanel3Layout.setHorizontalGroup(
            cupPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cupPanel3Layout.setVerticalGroup(
            cupPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel4.add(cupPanel3);
        cupPanel3.setBounds(140, 110, 20, 130);

        cupPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cupPanel5Layout = new javax.swing.GroupLayout(cupPanel5);
        cupPanel5.setLayout(cupPanel5Layout);
        cupPanel5Layout.setHorizontalGroup(
            cupPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        cupPanel5Layout.setVerticalGroup(
            cupPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel4.add(cupPanel5);
        cupPanel5.setBounds(70, 110, 10, 130);

        cupPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cupPanel4Layout = new javax.swing.GroupLayout(cupPanel4);
        cupPanel4.setLayout(cupPanel4Layout);
        cupPanel4Layout.setHorizontalGroup(
            cupPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        cupPanel4Layout.setVerticalGroup(
            cupPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel4.add(cupPanel4);
        cupPanel4.setBounds(160, 110, 10, 120);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("The Cup Capacity is 0.25  litter ");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 10, 280, 22);

        jButton9.setBackground(new java.awt.Color(0, 153, 153));
        jButton9.setText("Pour");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(60, 290, 90, 30);

        cupTextArea.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        cupTextArea.setForeground(new java.awt.Color(0, 102, 102));
        jPanel4.add(cupTextArea);
        cupTextArea.setBounds(360, 70, 380, 320);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\cup1.jpg")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11);
        jLabel11.setBounds(40, 60, 160, 190);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Cups information ");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(500, 40, 180, 30);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7);
        jPanel7.setBounds(70, 230, 100, 10);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8);
        jPanel8.setBounds(60, 100, 10, 100);

        javax.swing.GroupLayout cupPanel6Layout = new javax.swing.GroupLayout(cupPanel6);
        cupPanel6.setLayout(cupPanel6Layout);
        cupPanel6Layout.setHorizontalGroup(
            cupPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cupPanel6Layout.setVerticalGroup(
            cupPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(cupPanel6);
        cupPanel6.setBounds(60, 100, 20, 100);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("you should click cup to drink coctail ");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 330, 370, 50);

        jButton12.setBackground(new java.awt.Color(153, 0, 102));
        jButton12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        jButton12.setText("Clear");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(450, 540, 120, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setText("To clear blender and cups pleas enter clear button :");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(80, 550, 360, 17);

        jTabbedPane1.addTab("pour", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(24, 0, 786, 716);

        jMenuBar1.setBackground(new java.awt.Color(153, 0, 153));

        jMenu1.setText("File");

        jMenu3.setText("save");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenu3);

        jMenuItem6.setText("open");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem6MouseClicked(evt);
            }
        });
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    
    
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Ingredients  f=new Fruits("Apple",130,0.2,new Color(219,46,11));
         blender.add(f); 
         this.show1();
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Suger f=new Suger();
                blender.add(f);
               this.show1();
                    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Fruits f=new Fruits("Banana",110,0.125,new Color(255,255,50));
             blender.add(f);
             this.show1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      Fruits   f=new Fruits("Pineapple",50,0.11,new Color(255,255,130));
                      blender.add(f);
                      this.show1();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        // blend coctail 
        blender.blend(blender);
        
        java.awt. Color  color;
        
        
        if(blender.getVolume()==0)color= new java.awt.Color(204,255,255);
        else{Color c1=blender.getColor();
            color=new  java.awt.Color(c1.getR(),c1.getG(),c1.getB()); 
            
            
        }
         color1Panel.setBackground(color);
         color2Panel.setBackground(color);
         color3Panel.setBackground(color);
        color1Panel1.setBackground(color);
        
        caloriesLable.setText("the Total Caloreis in Blende is : " + blender.getCalories() + "  caloreis");
        caloriesLabel2.setText("The Total volume is : "  +blender.getVolume() + "  litters" );
        cups.clear();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Fruits  f=new Fruits("Orange",80,0.15,new Color(255,179,25));
                     blender.add(f);
                     this.show1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      Fruits  f=new Fruits("Strawberries",50,0.125,new Color(252,90,141));
                      blender.add(f);
                      this.show1();
                 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Fruits  f=new Fruits("kiwi",90,0.15,new Color(176,191,26));
                      blender.add(f);
                      this.show1();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Milk f=new Milk("milk",300,0.5, new Color(255,255,255));
                    blender.add(f);
                    this.show1();
      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       
        
        int index= ingredientsList.getSelectedIndex();
        blender.getIng().remove(index);
       this.show1();
    
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    
        java.awt.Color color = new java.awt.Color(255,255,255);
        if(b1){
            JOptionPane.showMessageDialog(this, "your cup is full you shold drink your cup ");
        }
            
        //pouring in cups
        else{
        Cup cup1;
       cup1 = new Cup();
       cups.add(cup1);
       
          if(blender.getVolume()==0){
                  blender.getIng().clear();
      this.show1();
          }
          
       else{
          Color c1=blender.getColor();
       color =new java.awt.Color(c1.getR(),c1.getG(),c1.getB());
       }
          
          
          String ing ="";
       for(int i=0;i<blender.getIng().size() ;i++){
           ing   += blender.getIng().get(i).getName() + "\n";
       }
          
        blender.pour(cup1, blender);
          if(cup1.getVolume()==0){cupTextArea.setText(""); 
          b1=false;
        }
        
       else{
       String str=   "Cup number  : "  +  cups.size()  + "  \n" + blender.getStr() + "\n " + "the  cup information : \n this cup contain : \n " +ing  + cup1.toString() ;
       cupTextArea.setText(str); 
          b1=true;}
      
       
    
       
       cupPanel1.setBackground(color);
       cupPanel2.setBackground(color);
       cupPanel3.setBackground(color);
       cupPanel4.setBackground(color);
       cupPanel5.setBackground(color);
       
       
        
        
        
       
   
        double r1;
       if(blender.getCalories() >1) r1= blender.getCalories(); 
       else r1=0;

        caloriesLable.setText("the Total Caloreis in Blende is : " +  r1 + "  caloreis");
        caloriesLabel2.setText("The Total volume is : "  +blender.getVolume() + "  litters" );
        
       
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
             java.awt.Color  color =new java.awt.Color(255,255,255);
       cupPanel1.setBackground(color);
       cupPanel2.setBackground(color);
       cupPanel3.setBackground(color);
       cupPanel4.setBackground(color);
       cupPanel5.setBackground(color);
       cupTextArea.setText("");
        JOptionPane.showMessageDialog(this, "you finishid the cup ");
        b1=false;
       
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       
        
          try {
              
              ObjectInputStream in2=new ObjectInputStream(new FileInputStream("Blender.dat"));
              
              this.blender=(Blender) in2.readObject();
              in2.close();
             ObjectInputStream in3=new ObjectInputStream(new FileInputStream("Cup.dat"));
             cups=(ArrayList<Cup>) in3.readObject();
              in3.close();
              Color c1 = blender.getColor();
             java.awt.Color color =new java.awt.Color(c1.getR(),c1.getG(),c1.getB() );
             // blender color
         color1Panel.setBackground(color);
         color2Panel.setBackground(color);
         color3Panel.setBackground(color);
         color1Panel1.setBackground(color);
   
       
        double r1;
       if(blender.getCalories() >1) r1= blender.getCalories(); 
       else r1=0;
       
         caloriesLable.setText("the Total Caloreis in Blende is : " +  r1 + "  caloreis");
        caloriesLabel2.setText("The Total volume is : "  +blender.getVolume() + "  litters" );
        
        
        String str[];
        str= new String[0];
        ingredientsList.setListData(str);
        
        
        if(cups.size()>0)
        {
            
                //cup color
      cupPanel1.setBackground(color);
       cupPanel2.setBackground(color);
       cupPanel3.setBackground(color);
       cupPanel4.setBackground(color);
       cupPanel5.setBackground(color);
           String ing ="";
       for(int i=0;i<blender.getIng().size() ;i++){
           ing   += blender.getIng().get(i).getName() + "\n";
       }
        
           String str1=   "Cup number  : "  +  cups.size()  + "  \n" + blender.getStr() + "\n " + "the  cup information : \n this cup contain : \n " +ing  + cups.get(cups.size()-1).toString() ;
       cupTextArea.setText(str1); 
       
       b1=true;}
        
        
        
       JOptionPane.showMessageDialog(this,"opend");
              
          } catch (FileNotFoundException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage() + "doesnt exist");
          } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() + "wrong");
          } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage() +" class not found");
          }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
 
           
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
               String FileName1="ingredients.dat";
               for(int i=0;i<blender.getIng().size();i++)
                   ingList.add(blender.getIng().get(i));
     
          try {
                ObjectOutputStream out1=new ObjectOutputStream(new FileOutputStream(FileName1));
               out1.writeObject(ingList);
                
              out1.close();
               ObjectOutputStream out2=new ObjectOutputStream(new FileOutputStream("Blender.dat"));
              out2.writeObject(blender);
              out2.close();
             
               ObjectOutputStream  out3=new ObjectOutputStream(new FileOutputStream("Cup.dat"));
             out3.writeObject(cups);
              
               out3.close();
                JOptionPane.showMessageDialog(this,"you saved succesfully");
      
          } catch (FileNotFoundException ex) {
              JOptionPane.showMessageDialog(jMenu1, ex.getMessage());
          } catch (IOException ex) {
             JOptionPane.showMessageDialog(jMenu1, ex.getMessage());
          }
        
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MouseClicked

    }//GEN-LAST:event_jMenuItem6MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        blender.getIng().clear();
        this.show1();
        cups.clear();
        java.awt.Color color= new java.awt.Color(204,255,255);
          color1Panel.setBackground(color);
         color2Panel.setBackground(color);
         color3Panel.setBackground(color);
         color1Panel1.setBackground(color);
         color= new java.awt.Color(255,255,255);
         
       cupPanel1.setBackground(color);
       cupPanel2.setBackground(color);
       cupPanel3.setBackground(color);
       cupPanel4.setBackground(color);
       cupPanel5.setBackground(color);
       
       caloriesLable.setText("");
        caloriesLabel2.setText("");
         cupTextArea.setText(""); 
         b1=false;
    }//GEN-LAST:event_jButton12ActionPerformed

    
    
    
    
          public void show1(){
        String [] str;
        str= new String[blender.getIng().size()];
        for(int i=0;i<blender.getIng().size();i++){
            str[i]=blender.getIng().get(i).getName();
        }
            
            
        ingredientsList.setListData(str);
    }
    
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
           try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoctailShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoctailShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoctailShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoctailShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable(){
             public void run() {
            new CoctailShop().setVisible(true);
             }
        });
    }

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caloriesLabel2;
    private javax.swing.JLabel caloriesLable;
    private javax.swing.JPanel color1Panel;
    private javax.swing.JPanel color1Panel1;
    private java.awt.Panel color2Panel;
    private javax.swing.JPanel color3Panel;
    private javax.swing.JPanel cupPanel1;
    private javax.swing.JPanel cupPanel2;
    private javax.swing.JPanel cupPanel3;
    private javax.swing.JPanel cupPanel4;
    private javax.swing.JPanel cupPanel5;
    private javax.swing.JPanel cupPanel6;
    private java.awt.TextArea cupTextArea;
    private javax.swing.JList<String> ingredientsList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
